# Generated by Django 3.0.8 on 2020-08-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_descrpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descrpt',
            new_name='description',
        ),
    ]
