# Generated by Django 3.0.8 on 2020-08-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200820_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='Active',
            new_name='Like',
        ),
    ]
